name: Create torrent using py3createtorrent
on:
  push:
    paths:
      - ".github/workflows/py3createtorrent.yml"
      
env:
  name: "The Agora Financial Copy School System"
  comment: "The Agora Financial Copy School System by torrent-webseed-creator"
  url: "http://sv5.mshare.space/td/H5olstvh3G"
  file_name: "The Agora Financial Copy School System.rar"
  piece_size: 0 # 0 for automatic calculation, or use the recommended piece size on the README.md file
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install py3createtorrent
        run: sudo pip3 install py3createtorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using py3createtorrent
        run: py3createtorrent -p $piece_size -c "$comment" -o "${name}.torrent" --webseed "$url" "$file_name" # Tested on 1.0.0
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
